# Generated by Django 5.2.1 on 2025-06-26 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_customuser_bch_pubkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bch_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bch_pubkey',
        ),
    ]
