# Generated by Django 5.2.1 on 2025-06-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_customuser_bch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='contract_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
