# Generated by Django 5.2.1 on 2025-07-01 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_room_contract_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
