# Generated by Django 5.2.1 on 2025-07-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_room_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='min_balance_required',
            field=models.DecimalField(decimal_places=8, default=0.00018, help_text='Minimum BCH balance required to join this room', max_digits=10),
        ),
    ]
