# Generated by Django 5.2.1 on 2025-07-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_room_min_balance_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='message_fee',
            field=models.DecimalField(decimal_places=8, default=1.8e-05, help_text='BCH fee required to send a message in this room', max_digits=10),
        ),
    ]
