# Generated by Django 5.2.1 on 2025-07-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_room_message_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of users allowed in this room(0 = unlimited)'),
        ),
    ]
